### ISSUE TITLE
need more docments.....

### ISSUE THREAD

**Issue by lemonhall** [uber/ringpop-common#38]
PLEASE write more docs....

**Comment by Motiejus** [comment]
Hello @lemonhall! We're very excited about your interest on ringpop.

More documentation is in the pipeline ([literally][1]: we published more documentation, but it's currently [stuck in rtfd][2]). We certainly did not abandon it, and will keep adding more and more in due time.

Is there something in particular you would like to know about ringpop you find lacking in the documentation? If you have anything specific would like to know about, please let us know here, and we'll do our best to clear things up.

[1]: https://readthedocs.org/projects/ringpop/builds/
[2]: https://github.com/rtfd/readthedocs.org/issues/2047

**Comment by Motiejus** [comment]
Documentation pushing is un-stuck, and there are no updates on the thread. Closing.

If you feel like we can still clarify something even more, please open a new issue.
